# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_ICO',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание ICO'),
        ),
        migrations.AddField(
            model_name='product',
            name='step_by_step',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание step_by_step'),
        ),
    ]
