# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-07 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190707_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_ico',
        ),
    ]
