# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-07 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_additional_ico'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_ico',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание ICO'),
        ),
    ]
